desc: Ask a cow to say something smart
# 'params' are injected as environmetal variables
# Note: There very first 'param' is visible on the Feed page
params:
  - SLEEP: 5

tasks:
  - name: Waking up a cow
    run: sleep ${SLEEP}

  - name: Cow says
    run: fortune | cowsay
    # `run` is executed when the condition in `when` evaluates to `true`
    # The condition uses `[[` syntax from bash (https://devhints.io/bash#conditionals)
    when: $USER == joe
    env:
      KEY: SECRET
      HTTPS: true

# List of patterns according to https://golang.org/pkg/path/filepath/#Match
# related to the workspace directory
# Note:
#  - artifacts are collected only for builds with status `finished` or `failed`
#  - `on_finished`, `on_failed` tasks are executed before artifacts are collected
#  - `finally` tasks are executed after artifacts are collected
artifacts:
  - "*.tar.gz"

# Automatically run the job every configured interval (cron expression)
# More info https://godoc.org/github.com/robfig/cron
interval: "@daily"

# Abort the job if it takes more than specified amount of time to finish
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
timeout: 5m30s

# Adjust build position in the queue
priority: 10

# Designates if parallel builds of the same job are allowed
allow_parallel: no

# List of tasks executed on build's status change
# Available handlers:
#  - on_pending
#  - on_running
#  - on_aborted
#  - on_failed
#  - on_finished
# Note: If one of the commands failed, it doesn't fail the whole build
on_pending:
  - name: Log a call
    run: logger "Looking for a suitable cow"

# List of tasks that are always executed
finally:
  - name: List all files
    run: ls -alh

# Available environmetal variables:
# "WAKE_BUILD_ID" - current build id, e.g. 169
# "WAKE_BUILD_WORKSPACE" - path to the build's workspace, e.g. ~/workspace/
# "WAKE_JOB_NAME" - name of the job, e.g. ask_a_cow
# "WAKE_JOB_PARAMS" - URL encoded `params` of the job. Useful to start another
#                     job with the same params, e.g. "sleep=5&print=true"
# "WAKE_CONFIG_DIR" - path to the directory with all job configuration files,
#                     e.g. ~/jobs/
# "WAKE_URL" - URL of the service, e.g. https://myci.space/
