desc: Ask a cow to say something smart
# 'params' are injected as environmetal variables
params:
  - SLEEP: 5

tasks:
  - name: Waking up a cow
    command: sleep ${SLEEP}

  - name: Cow says
    command: fortune | cowsay

# List of patterns according to https://golang.org/pkg/path/filepath/#Match
# related to the workspace directory
artifacts:
  - "*.tar.gz"

# Automatically run the job every configured interval (cron expression)
# More info https://godoc.org/github.com/robfig/cron
interval: "@daily"

# List of tasks executed on build's status change
# Available handlers:
#  - on_pending
#  - on_running
#  - on_aborted
#  - on_failed
#  - on_finished
# Note: If one of the commands failed, it doesn't fail the whole build
on_pending:
  - name: Log a call
    command: logger "Looking for a suitable cow"

# Available environmetal variables:
# WAKE_BUILD_ID - current build id, e.g. 169
# WAKE_BUILD_WORKSPACE - path to the build's workspace
# WAKE_JOB_NAME - name of the job, e.g. ask_a_cow
# WAKE_CONFIG_DIR - path to the directory with all job configuration files
# WAKE_URL - URL of the service, e.g. https://myci.space/
