name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go

    - name: Check out code into the Go module directory
      use: actions/checkout@master
      path: ${{ go.module-path }}

    - name: Get go dependencies
      working-directory: ${{ go.module-path }}/src/backend
      run: |
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        go get github.com/GeertJohan/go.rice/rice
        dep ensure

    - name: Build frontend
      working-directory: ${{ go.module-path }}/src/frontend
      run: |
        npm install
        npm run build

    - name: Build application
      working-directory: ${{ go.module-path }}/src/backend
      run: |
        rice embed-go
        go build 
